name: google_places_autocomplete
description: Seamlessly integrate Google Places API into your Flutter app with this package. Get location autocomplete, detailed place info, and flexible UI implementation.

version: 0.0.4
homepage: https://github.com/Cuboid-Inc/google_places_autocomplete
repository: https://github.com/Cuboid-Inc/google_places_autocomplete

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

topics:
  - network
  - http
  - google-places
  - flexible-ui
  - map

flutter:
